---
openapi: 3.0.3
info:
  title: ProblemDetails 
  description: |-
    The ProblemDetails object provides detailed information about an errors that occurred during an API call execution. 
    
    This problem object :
    
    * **conforms** to the [RFC9457](https://www.rfc-editor.org/info/rfc9457) (formerly [RFC7807](https://tools.ietf.org/html/rfc7807)).
    
    * is **extended** with the following properties:
    
        * **errors** - an array of errors providing contextual information on the root cause of the problem.
    
    
    The ProblemDetails referenced by this domain utilize the [SmartBear Problems Registry](https://problems-registry.smartbear.com/).
           
  version: '1.0.0'
components:
  schemas:
    
      
    ProblemDetails:
      type: 'object'
      properties:
        type:
          type: 'string'
          description: 'A URI reference that identifies the problem type.'
          format: 'uri'
          maxLength: 1024
        status:
          type: 'integer'
          description: 'The HTTP status code generated by the origin server for this occurrence of the problem.'
          format: 'int32'
          minimum: 100
          maximum: 599
        title:
          type: 'string'
          description: 'A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.'
          maxLength: 1024
        detail:
          type: 'string'
          description: 'A human-readable explanation specific to this occurrence of the problem.'
          maxLength: 4096
        errors:
          $ref: '#/components/schemas/ProblemDetails'
      required:
        - 'type'
        - 'status'
        - 'title'
        - 'detail'
        
    Errors:
      type: 'array'
      description: 'An array of error details to accompany a problem details response.'
      minItems: 1
      maxItems: 1000
      items:
        $ref: '#/components/schemas/ProblemDetails'
        
    ErrorDetail:
      type: 'object'
      description: 'An object to provide explicit details on a problem towards an API consumer.'
      properties:
        detail:
          type: 'string'
          description: 'A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.'
          maxLength: 4096
        source:
          type: 'string'
          description: 'The source of the error, e.g. the name of a header, query or path parameter, or a JSON pointer to a specific request body property.'
          maxLength: 1024
        value:
          type: 'string'
          description: 'The value that has caused the error, e.g. the value passed in as a header, query or path parameter, or a request body property that lead to the error.'
        code:
          type: 'string'
          description: 'A string containing additional provider specific codes to identify the error context.'
          maxLength: 50
      required:
        - 'detail'
        
  responses:
    BadRequest:
      description: 'The request was malformed or could not be processed.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            invalidRequestSchema:
              $ref: '#/components/examples/invalid-request-schema'            
    Unauthorized:
      description: 'Access token is not set or invalid.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            unauthorized:
              $ref: '#/components/examples/unauthorized'
    Forbidden:
      description: 'The requestor is not authorized to perform this operation on the resource.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            forbidden:
              $ref: '#/components/examples/forbidden'
    NotFound:
      description: 'The requested resource was not found.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            notFound:
              $ref: '#/components/examples/not-found'
    ServerError:
      description: 'The server encountered an unexpected error'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            serverError:
              $ref: '#/components/examples/server-error'
    ServiceUnavailable:
      description: 'The service requested is unavailable'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            serviceUnavailable:
              $ref: '#/components/examples/service-unavailable'
              
  examples:
    invalid-request-schema:
      description: 'Representation of a 400 Bad Request response where the request has failed schema validation.'
      value:
        type: 'https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1'
        status: 400
        title: 'Request Schema Error'
        detail: 'The request failed schema validation.'
        errors:
          - detail: 'The request is missing the required query parameter {id}'
            code: 'S002'
            source: 'id'          
    unauthorized:
      value:
        type: 'https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2'
        title: 'Unauthorized'
        detail: 'Access token not set or invalid. The requested resource could not be returned'
        status: 401
    forbidden:
      value:
        type: 'https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4'
        title: 'Forbidden'
        detail: 'The resource could not be returned as the requestor is not authorized'
        status: 403
    not-found:
      value:
        type: 'https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.5'
        title: 'Not found'
        detail: 'The requested resource was not found'
        status: 404
    server-error:
      value:
        type: 'https://datatracker.ietf.org/doc/html/rfc9110#section-15.6.1'
        title: 'Server Error'
        detail: 'The server encountered an unexpected error'
        status: 500
    service-unavailable:
      value:
        type: 'https://datatracker.ietf.org/doc/html/rfc9110#section-15.6.4'
        title: 'Service Unavailable'
        detail: 'The service is currently unavailable'
        status: 503
paths: {}
