services:
  keeperdata_api:
    build:
      args:
        TARGETARCH: x64
    labels:
      com.microsoft.visual-studio.project-name: "KeeperData.Api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5555
      - Mongo__DatabaseUri=mongodb://kda_mongodb:27017
      - ApiClients__DataBridgeApi__BaseUrl=http://keeperdata_bridge:5560/
      - ApiClients__DataBridgeApi__BridgeApiSubscriptionKey=
      - ApiClients__DataBridgeApi__ServiceName=
      - ApiClients__DataBridgeApi__XApiKey=
      - ApiClients__DataBridgeApi__UseFakeClient=true
      - AdminEndpointsEnabled=true
      - AuthenticationConfiguration__EnableApiKey=true
      - AuthenticationConfiguration__ApiGatewayExists=false
      - AuthenticationConfiguration__Authority=

    ports:
      - "5555"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      # Mount seed files directly for Rider Fast Mode
      - ./src/KeeperData.Infrastructure/Data/Seed:/app/Data/Seed:ro
