name: 'keeperdata_api'
services:
  mongodb:
    container_name: kda_mongodb
    hostname: kda_mongodb
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27019:27017'
    volumes:
      - mongodb-data:/data/db
    restart: always

  keeperdata_api:
    container_name: "keeperdata_api"
    platform: linux
    image: keeperdata_api
    build: ./
    ports:
      - '5555:5555'
    depends_on:
      mongodb:
        condition: service_started
    environment:
      PORT: 5555
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    name: cdp-tenant
