@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Boundaries
System_Boundary(cdp, "CDP") {
  System(keeperBridge, "Keeper Data Bridge", "Loads data from External S3, decrypts and stores on Internal S3, generates reports, surfaces data via OData")
  System(keeperApi, "Keeper Data API", "Transforms raw data, forms business domain models, exposes data")
}

System_Boundary(defra, "External DEFRA") {
  System_Ext(externalS3, "External S3", "Stores raw encrypted data files")
}

System_Boundary(liLtd, "LI Ltd") {
  System_Ext(externalApps, "Applications", "Consumer of Keeper Reference Data")
}

System_Boundary(dataCleanse, "Data Cleanse") {
  Person_Ext(externalUsers, "Users", "Consumer of Keeper Reference Data comparison reports")
}

' Relationships
Rel(externalApps, keeperApi, "Queries business domain models")
Rel(externalUsers, keeperBridge, "Reviews comparison reports")
Rel(keeperBridge, externalS3, "Loads encrypted data")
Rel(keeperApi, keeperBridge, "Scans for changes & imports data")

@enduml