{
 "title": "ls-keeper-data-api (custom)",
 "tags": [
  "custom",
  "service",
  "protected",
  "ls-keeper-data-api"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "SAM Daily Scan Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "entity": "Holdings", "metric_name": "daily_scan_items_found", "scan_type": "SAM" },
     "label": "Daily SAM Holdings",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Holders", "metric_name": "daily_scan_items_found", "scan_type": "SAM" },
     "label": "Daily SAM Holders",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Herds", "metric_name": "daily_scan_items_found", "scan_type": "SAM" },
     "label": "Daily SAM Herds",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Parties", "metric_name": "daily_scan_items_found", "scan_type": "SAM" },
     "label": "Daily SAM Parties",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Holdings", "metric_name": "daily_scan_items_found", "scan_type": "CTS" },
     "label": "Daily CTS Holdings",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Agents", "metric_name": "daily_scan_items_found", "scan_type": "CTS" },
     "label": "Daily CTS Agents",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Keepers", "metric_name": "daily_scan_items_found", "scan_type": "CTS" },
     "label": "Daily CTS Keepers",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Holdings", "metric_name": "bulk_scan_items_found", "scan_type": "SAM" },
     "label": "Bulk SAM Holdings",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Holders", "metric_name": "bulk_scan_items_found", "scan_type": "SAM" },
     "label": "Bulk SAM Holders",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "entity": "Holdings", "metric_name": "bulk_scan_items_found", "scan_type": "CTS" },
     "label": "Bulk CTS Holdings",
     "metricName": "countTotal",
     "namespace": "ls-keeper-data-api",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Overall Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Keeper Data Api Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": {
      "keeperdata.healthcheck": "overall"
     },
     "metricName": "keeperdataHealthStatus",
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Messages In Intake Queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "QueueName": "ls_keeper_data_intake_queue" },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Messages In DLQ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "ls_keeper_data_intake_queue-deadletter"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Detailed Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Keeper Data Bridge API Connectivity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "dimensions": {
      "keeperdata.healthcheck": "http-client-DataBridgeApi"
     },
     "metricName": "keeperdataHealthStatus",
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MongoDB Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "dimensions": {
      "keeperdata.healthcheck": "mongodb"
     },
     "metricName": "keeperdataHealthStatus",
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Intake Event Queue Connectivity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "dimensions": {
      "keeperdata.healthcheck": "intake-event-consumer"
     },
     "metricName": "keeperdataHealthStatus",
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Batch Completion Event Queue Connectivity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "dimensions": {
      "keeperdata.healthcheck": "batch-completion-publisher"
     },
     "metricName": "keeperdataHealthStatus",
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Amazon S3 Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "dimensions": {
      "keeperdata.healthcheck": "aws_s3"
     },
     "metricName": "keeperdataHealthStatus",
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Errors Logged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name:\"ls-keeper-data-api\" AND log.level:error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Warnings Logged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name:\"ls-keeper-data-api\" AND log.level:warning",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "metricName": "countTotal",
     "metricQueryType": 1,
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ls-keeper-data-api", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "operation", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "countTotal", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(countTotal) FROM \"ls-keeper-data-api\" GROUP BY \"operation\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Other",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "metricName": "countTotal",
     "metricQueryType": 1,
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ls-keeper-data-api", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "operation", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "countTotal", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(countTotal) FROM \"ls-keeper-data-api\" GROUP BY \"operation\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "metricName": "countTotal",
     "metricQueryType": 1,
     "namespace": "ls-keeper-data-api",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ls-keeper-data-api", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "operation", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "countTotal", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(countTotal) FROM \"ls-keeper-data-api\" GROUP BY \"operation\"",
     "statistic": "Average"
    }
   ]
  }
 ]
}